
[root]
shape = "column" 
width = "100%"
height = "100%"

[root.header]
shape = "embed"
layout = "{header}"

[root.contents]
shape = "scroll_column"
width = "100%"
height = "100%"
horizontal_padding = "20px"
bottom_outer_padding = "80px"
custom_class = "{custom_class}"

[root.footer]
shape = "embed"
layout = "{footer}"