
[root]
shape = "scroll_column" 
width = "100%"
height = "100%"

[root.header]
shape = "embed"
layout = "{header}"

[root.contents]
shape = "column"
width = "100%"
height = "wrap"
horizontal_padding = "20px"
bottom_outer_padding = "80px"

[root.footer]
shape = "embed"
layout = "{footer}"