
[root]
shape = "column" 
width = "100%"
height = "100%"

[root.header]
shape = "embed"
layout = "{header}"

[root.contents]
shape = "scroll_column"
width = "100%"
height = "100%"
custom_class = "{custom_class} pl-[20px] pr-[20px] pb-[80px]"

[root.footer]
shape = "embed"
layout = "{footer}"