[nav]
home = "/"
service.etc1 = "etc1"
service.etc2 = "etc2"
service.etc3 = "etc3"
menu = "menu"
end = "end"

[theme]
night = false

[footer]
title = "220022"
sns.facebook = "Hey"

[basic]
created = "2025-01-01 22:10:23"
tag = "root"
