[nav]
home = "/"
language.rust = "/language/rust"
language.rust2 = "language/rust"
service.etc2 = "etc2"
service.etc3 = "etc3"
service2.etc2 = "etc2"
service2.etc3 = "etc3"
rust = "rust"

[theme]
night = false

[footer]
title = "© 2025 Rubinsharks™. All Rights Reserved."
sns.facebook = "https://www.meta.com/"
sns.github = "https://www.github.com/"

[basic]
title = "Rubinsharks"
created = "2025-01-01 22:10:23"
tags = "root"
